{
 "title": "Chaos Dashboard",
 "description": "ASP.NET Core metrics from OpenTelemetry",
 "tags": [
  "dotnet",
  "prometheus",
  "aspnetcore"
 ],
 "time": { "from": "2025-10-09T17:18:14.328Z", "to": "2025-10-09T17:28:23.890Z" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(http_server_active_requests,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(http_server_active_requests{job=~\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Verbrauch pro Pod/min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n  sum(rate(container_cpu_usage_seconds_total{namespace=\"target\"}[1m])) by (pod)\n)\n/\n(\n  sum(kube_pod_container_resource_limits{namespace=\"target\", resource=\"cpu\"}) by (pod)\n)\n* 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Speicher Verbrauch pro Pod/min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_memory_usage_bytes{namespace=\"target\"}[1m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fehlerrate/min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_bucket{job=~\"$job\", instance=~\"$instance\", http_response_status_code=~\"4..\"}[1m]) or vector(0)) / sum(rate(http_server_request_duration_seconds_bucket{job=~\"$job\", instance=~\"$instance\"}[1m]))",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(rate(http_server_request_duration_seconds_bucket{job=~\"$job\", instance=~\"$instance\", http_response_status_code=~\"5..\"}[1m]) or vector(0)) / sum(rate(http_server_request_duration_seconds_bucket{job=~\"$job\", instance=~\"$instance\"}[1m]))",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "Antwortzeit/min",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum(\n    rate(\n      http_server_request_duration_seconds_bucket{\n        job=~\"$job\",\n        instance=~\"$instance\",\n        http_route!~\"/health.*|/metrics.*\"\n      }[1m]\n    )\n  ) by (le)\n)\n",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(\n  0.75,\n  sum(\n    rate(\n      http_server_request_duration_seconds_bucket{\n        job=~\"$job\",\n        instance=~\"$instance\",\n        http_route!~\"/health.*|/metrics.*\"\n      }[1m]\n    )\n  ) by (le)\n)\n",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(\n  0.90,\n  sum(\n    rate(\n      http_server_request_duration_seconds_bucket{\n        job=~\"$job\",\n        instance=~\"$instance\",\n        http_route!~\"/health.*|/metrics.*\"\n      }[1m]\n    )\n  ) by (le)\n)\n",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum(\n    rate(\n      http_server_request_duration_seconds_bucket{\n        job=~\"$job\",\n        instance=~\"$instance\",\n        http_route!~\"/health.*|/metrics.*\"\n      }[1m]\n    )\n  ) by (le)\n)\n",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(\n  0.98,\n  sum(\n    rate(\n      http_server_request_duration_seconds_bucket{\n        job=~\"$job\",\n        instance=~\"$instance\",\n        http_route!~\"/health.*|/metrics.*\"\n      }[1m]\n    )\n  ) by (le)\n)\n",
     "legendFormat": "p98"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum(\n    rate(\n      http_server_request_duration_seconds_bucket{\n        job=~\"$job\",\n        instance=~\"$instance\",\n        http_route!~\"/health.*|/metrics.*\"\n      }[1m]\n    )\n  ) by (le)\n)\n",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(\n  0.999,\n  sum(\n    rate(\n      http_server_request_duration_seconds_bucket{\n        job=~\"$job\",\n        instance=~\"$instance\",\n        http_route!~\"/health.*|/metrics.*\"\n      }[1m]\n    )\n  ) by (le)\n)\n",
     "legendFormat": "p99.9"
    }
   ]
  },
  {
   "title": "Anfragenvolumen/min",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (http_route, http_request_method, method_route) (\n    label_join(\n      floor(\n        increase(\n          http_server_request_duration_seconds_count{\n            http_route!~\"/health.*|/metrics.*\"\n          }[1m]\n        )\n      ),\n      \"method_route\", \" \", \"http_request_method\", \"http_route\"\n    )\n  )",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "Gesamt angeforderte Bestellungen",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (otel_scope_name) (round(increase(orders_requested_number_total[$__range])))",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "Top 10 Endpunkte mit unbehandelten Exceptions",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 14 },
   "targets": [
    {
     "expr": "  topk(10,\r\n  sum by (http_route, http_request_method, method_route) (\r\n    label_join(ceil(increase(http_server_request_duration_seconds_count{job=~\"$job\", instance=~\"$instance\", http_route!=\"\", error_type!=\"\"}[$__range])), \"method_route\", \" \", \"http_request_method\", \"http_route\")\r\n  ))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Gesamt abgeschlossene Bestellungen",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (otel_scope_name) (round(increase(orders_completed_number_total[$__range])))",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "Top 10 Requested Endpoints",
   "type": "table",
   "gridPos": { "h": 5, "w": 7, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "topk(10,\r\n  sum by (http_route, http_request_method, method_route) (\r\n    label_join(\r\n      floor(\r\n        increase(\r\n          http_server_request_duration_seconds_count{\r\n            http_route!~\"/health.*|/metrics.*\"\r\n          }[$__range]\r\n        )\r\n      ),\r\n      \"method_route\", \" \", \"http_request_method\", \"http_route\"\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Current Connections",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kestrel_active_connections{job=~\"$job\", instance=~\"$instance\", service=\"order-service\"})",
     "legendFormat": "active connections"
    }
   ]
  },
  { "title": "Annotations", "type": "annolist", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "{env=\"production\"} |~ \"(?i)error|warning\"\n",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Current Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 45 },
   "targets": [
    {
     "expr": "sum(http_server_active_requests{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "active requests"
    }
   ]
  },
  {
   "title": "Requests HTTP Protocol",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (method_route) (\r\n    label_replace(ceil(increase(http_server_request_duration_seconds_count{job=~\"$job\", instance=~\"$instance\"}[$__range])), \"method_route\", \"http/$1\", \"network_protocol_version\", \"(.*)\")\r\n  )",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Requests Secured",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (url_scheme) (\r\n    ceil(increase(http_server_request_duration_seconds_count{job=~\"$job\", instance=~\"$instance\"}[$__range]))\r\n  )",
     "legendFormat": "{{scheme}}"
    }
   ]
  }
 ]
}